version: 2.1
jobs:
  deploy1:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "73:61:5a:31:9c:71:65:b5:71:d5:d9:5f:4d:69:35:9e"
      - checkout
      - run:
          name: "Deploy"
          command: |
            chmod 400 secondtry.pem
            scp -v -o StrictHostKeyChecking=no -r index.html ubuntu@ip-172-31-37-110:/var/www/html/index.html
  deploy2:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "73:61:5a:31:9c:71:65:b5:71:d5:d9:5f:4d:69:35:9e"
      - checkout
      - run:
          name: "Deploy"
          command: |
            chmod 400 secondtry.pem
            scp -o StrictHostKeyChecking=no -r index.html ubuntu@ip-172-31-2-79:/var/www/html/index.html
workflows: 
  version: 2
  Ejecutar:
    jobs:
      - deploy1
      - request-testing:
          type: approval
          requires:
            - deploy1
      - deploy2:
          requires:
            - request-testing