version: 2.1
jobs:
  deploy1:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "73:61:5a:31:9c:71:65:b5:71:d5:d9:5f:4d:69:35:9e"
      - checkout
      - run:
          name: "Deploy"
          command: |
            chmod 600 "secondtry.pem"
            chmod 700 "secondtry.pem"
            ssh -i "secondtry.pem" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@ec2-54-145-193-18.compute-1.amazonaws.com
            scp -v -o StrictHostKeyChecking=no -r index.html ec2-54-145-193-18.compute-1.amazonaws.com:/var/www/html/index.html
            whoami
  deploy2:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "73:61:5a:31:9c:71:65:b5:71:d5:d9:5f:4d:69:35:9e"
      - checkout
      - run:
          name: "Deploy"
          command: |
            scp -o StrictHostKeyChecking=no -r index.html ec2-34-225-45-85.compute-1.amazonaws.com:/var/www/html/index.html
workflows: 
  version: 2
  Ejecutar:
    jobs:
      - deploy1
      - request-testing:
          type: approval
          requires:
            - deploy1
      - deploy2:
          requires:
            - request-testing