version: 2.1
jobs:
  ProductionEnvironment:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5a:c6:35:7a:2c:60:f6:48:4c:80:1c:ca:54:cc:8a:c0"
      - checkout
      - run:
          name: "Ejecucion"
          command: |
            echo "Estamos dentro"
            ls --all
            pwd
            echo "terminamos xd"
            scp -o StrictHostKeyChecking=no -r index.html ubuntu@18.211.47.194:/var/www/html/index.html
            
  DevelopmentEnvironment:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5a:c6:35:7a:2c:60:f6:48:4c:80:1c:ca:54:cc:8a:c0"
      - checkout
      - run:
          name: "Ejecucion"
          command: |
           echo "Estamos dentro"
            ls --all
            pwd
            echo "terminamos xd"
            scp -o StrictHostKeyChecking=no -r index.html ubuntu@18.211.47.194:/var/www/html/index.html
            
workflows: 
  version: 2
  Ejecutar:
    jobs:
      - DevelopmentEnvironment
      - request-testing:
          type: approval
          requires:
            - DevelopmentEnvironment
      - deployProduccion:
          requires:
            - request-testing
