version: 2.1
jobs:
  deployDesarrollo:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "69:88:a0:f6:61:80:6a:b3:f3:b6:4b:c6:ad:20:fd:a2"
      - checkout
      - run:
          name: "Deploy development"
          command: |    
            chmod 600 secondtry.pem
            scp -o -vv StrictHostKeyChecking=no -i secondtry.pem -r index.html ec2-54-145-193-18.compute-1.amazonaws.com:/var/www/html/index.html
  deployProduccion:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "69:88:a0:f6:61:80:6a:b3:f3:b6:4b:c6:ad:20:fd:a2"
      - checkout
      - run:
          name: "Deploy production"
          command: |
            scp -o StrictHostKeyChecking=no -r index.html ec2-34-225-45-85.compute-1.amazonaws.com:/var/www/html/index.html
workflows: 
  version: 2
  Ejecutar:
    jobs:
      - deployDesarrollo
      - request-testing:
          type: approval
          requires:
            - deployDesarrollo
      - deployProduccion:
          requires:
            - request-testing