version: 2.1
jobs:
  deploy1:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "57:5a:95:6d:fa:af:91:a2:84:aa:25:a1:b5:c7:55:09"
      - checkout
      - run:
          name: "Deploy"
          command: |
            scp -o "StrictHostKeyChecking=no" index.html ec2-user@ec2-3-85-55-102.compute-1.amazonaws.com:/var/www/html/index.html
  deploy2:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "57:5a:95:6d:fa:af:91:a2:84:aa:25:a1:b5:c7:55:09"
      - checkout
      - run:
          name: "Deploy"
          command: |
            scp -o "StrictHostKeyChecking=no" index.html ec2-user@ec2-34-201-25-105.compute-1.amazonaws.com:/var/www/html/index.html
workflows: 
  version: 2
  Ejecutar:
    jobs:
      - deploy1
      - request-testing:
          type: approval
          requires:
            - deploy1
      - deploy2:
          requires:
            - request-testing