version: 2.1
jobs:
  deployDesarrollo:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "73:61:5a:31:9c:71:65:b5:71:d5:d9:5f:4d:69:35:9e"
      - checkout
      - run:
          name: "Deploy development"
          command: |
            chmod 600 secondtry.pem
            scp -vv -o StrictHostKeyChecking=no -i secondtry.pem -r index.html ec2-54-145-193-18.compute-1.amazonaws.com:/var/www/html/index.html
  deployProduccion:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "73:61:5a:31:9c:71:65:b5:71:d5:d9:5f:4d:69:35:9e"
      - checkout
      - run:
          name: "Deploy production"
          command: |
            scp -o StrictHostKeyChecking=no -r index.html ec2-34-225-45-85.compute-1.amazonaws.com:/var/www/html/index.html
workflows: 
  version: 2
  Ejecutar:
    jobs:
      - deployDesarrollo
      - request-testing:
          type: approval
          requires:
            - deployDesarrollo
      - deployProduccion:
          requires:
            - request-testing