version: 2.1
jobs:
  deploy1:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "73:61:5a:31:9c:71:65:b5:71:d5:d9:5f:4d:69:35:9e"
      - checkout
      - run:
          name: "Deploy"
          command: |
            sudo chmod 700 ~/.ssh/
            sudo chmod 600 ~/.ssh/*
            sudo chown -R circleci ~/.ssh/
            sudo chgrp -R circleci ~/.ssh/
            scp -v -o StrictHostKeyChecking=no -r index.html ec2-user@ec2-3-85-55-102.compute-1.amazonaws.com:/var/www/html/index.html
  deploy2:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "73:61:5a:31:9c:71:65:b5:71:d5:d9:5f:4d:69:35:9e"
      - checkout
      - run:
          name: "Deploy"
          command: |
            sudo chmod 700 ~/.ssh/
            sudo chmod 600 ~/.ssh/*
            sudo chown -R circleci ~/.ssh/
            sudo chgrp -R circleci ~/.ssh/
            scp -o StrictHostKeyChecking=no -r index.html ec2-user@ec2-34-201-25-105.compute-1.amazonaws.com:/var/www/html/index.html
workflows: 
  version: 2
  Ejecutar:
    jobs:
      - deploy1
      - request-testing:
          type: approval
          requires:
            - deploy1
      - deploy2:
          requires:
            - request-testing