version: 2.1
jobs:
  deployDesarrollo:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b5:81:5e:e5:31:bf:2b:e0:ea:fb:f6:a5:4c:1f:5b:14"
      - checkout
      - run:
          name: "Deploy development"
          command: |
            sudo touch /home/circleci/.ssh/authorized_keys
            chmod 0600 secondtry.pem
            cd /home/circleci/.ssh
            sudo nano authorized_keys
            scp -v -o StrictHostKeyChecking=no -i a.pem -r index.html ec2-54-81-178-93.compute-1.amazonaws.com:/var/www/html/index.html
  deployProduccion:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b5:81:5e:e5:31:bf:2b:e0:ea:fb:f6:a5:4c:1f:5b:14"
      - checkout
      - run:
          name: "Deploy production"
          command: |
            scp -o StrictHostKeyChecking=no -r index.html ec2-54-81-178-93.compute-1.amazonaws.com:/var/www/html/index.html
workflows: 
  version: 2
  Ejecutar:
    jobs:
      - deployDesarrollo
      - request-testing:
          type: approval
          requires:
            - deployDesarrollo
      - deployProduccion:
          requires:
            - request-testing
